# Generated by Django 2.2 on 2021-08-24 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercrudmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 16, 16, 45, 687075)),
        ),
    ]
